### ISSUE TITLE
[BUG] Scene control buttons become invisible when Ernie's Layout is turned on

### ISSUE THREAD

**Issue by r-valyar** [ernieayala/ernies-modern-layout#147]
Scene control buttons become invisible when Ernie's Layout is turned on. Can be clicked on :)

![image](https://user-images.githubusercontent.com/63558984/147410692-ddaa7611-6178-4c62-9de7-56049738e8f2.png)

**Comment by keyxmakerx** [comment]
+1

**Comment by marman6** [comment]
+1

**Comment by Nealium104** [comment]
+1

**Comment by Ironxxx** [comment]
+1, makes the mod unuseable

**Comment by ernieayala** [comment]
Hey folks, in the middle of moving/packing, once I get settled in I will take a look at this again.

**Comment by zeteticl** [comment]
+1

**Comment by C4M3R0N808** [comment]
I came here to say this. V9 foundry if it matters. Disabling the Ernie layout options entirely can bring it back for me. But otherwise it is gone. I also notice some issues with overlap between the player menu and the hotbar Ernie's layout is enabled at all, even if everything else is off. Turning it off fixes the overlap here as well.

**Comment by patrickburk1988** [comment]
If you use a CSS-editing module like [Custom CSS](https://github.com/cswendrowski/FoundryVTT-Custom-CSS), you can add the following to your stylesheet as a quick-and-dirty fix:

```css
.-emu-layout body.-emu #controls .control-tools {
    opacity: 1;
}

.-emu-layout body.-emu #controls .control-tools.main-controls {
    left: 0;
}
```
